flock:
  children:
    arch-linux:
    ubuntu:

all-x86:
  hosts:
    rockhopper:
      ansible_host: localhost
    chinstrap:
      ansible_host: chinstrap
    afericangray:
      ansible_host: afericangray

arch-linux:
  children:
    base:
    arch-linux-away:
  vars:
    gitserver: macaroni


base:
  hosts:
    rockhopper:
      ansible_host: localhost

arch-linux-away:
  hosts:
    macaroni:
      ansible_host: macaroni
    chinstrap:
      ansible_host: chinstrap

away:
  children:
    ubuntu:
    arch-linux-away:

# these are local networks computers that are not
# from online
local-away:
  children:
    arch-linux-away:


ubuntu:
  hosts:
    afericangray:
      ansible_host: afericangray

away-x86:
  hosts:
    chinstrap:
      ansible_host: chinstrap
    afericangray:
      ansible_host: afericangray

local-away-x86:
  hosts:
    chinstrap:
      ansible_host: chinstrap

arm:
  hosts:
    macaroni:
      ansible_host: macaroni
