- name: Install Tmux
  hosts: all
  tasks:
    - name: install / update tmux
      ansible.builtin.package:
        name: tmux
        state: latest

- name: Copy Tmux Config
  hosts: away
  tasks:
    - name: Sync Tmux
      ansible.posix.synchronize:
        src: /home/j0hn/.tmux.conf
        dest: /home/j0hn/.tmux.conf
