- name: Update Arch Systems
  hosts: arch-linux
  become: true
  tasks:
    - name: Full System Upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: Shutdown Arch Away
  hosts: arch-linux-away
  become: true
  tasks:
    - name: Shutdown
      community.general.shutdown:

- name: Update Ubuntu Systems
  hosts: ubuntu
  become: true
  tasks:
    - name: Full System Upgrade
      apt:
        update_cache: true
        upgrade: true
    - name: Reboot
      ansible.builtin.reboot:

